# -*- coding: utf-8 -*-
"""
make_batches.py — one-time helper: writes N tiny launcher scripts
(doe_run_batch01.py, doe_run_batch02.py, ...), each hardcoded to one
disjoint slice of doe_config.N_POINTS rows. Ranges are computed here, so
there's no manual start/end typing per machine - and no way for two
batches to overlap. Copy whichever batch file (plus the rest of the
scripts folder) to each machine, then just `python doe_run_batchNN.py`
there - no arguments to remember.

Usage:
    python make_batches.py 10      # 10 rows per batch -> 15 files for 150 points
    python make_batches.py 5       # 5 rows per batch -> 30 files for 150 points
"""
import sys
from pathlib import Path
import doe_config as cfg

SCRIPT_DIR = Path(__file__).resolve().parent   # write batches next to make_batches.py itself, not wherever the shell's cwd happens to be

ROWS_PER_BATCH = int(sys.argv[1]) if len(sys.argv) > 1 else 10

n_batches = (cfg.N_POINTS + ROWS_PER_BATCH - 1) // ROWS_PER_BATCH
for b in range(n_batches):
    start = b * ROWS_PER_BATCH
    end = min(start + ROWS_PER_BATCH, cfg.N_POINTS)
    fname = SCRIPT_DIR / f"doe_run_batch{b+1:02d}.py"
    with open(fname, "w") as f:
        f.write(
            f"# Auto-generated by make_batches.py - handles rows {start}-{end-1}\n"
            f"import doe_run\n"
            f"doe_run.run_range({start}, {end})\n"
        )
    print(f"wrote {fname}  (rows {start}-{end-1})")
